package com.btba.dataobject;

import java.util.Date;

public class WxUserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.id
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_name
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    private String wxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.create_time
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.id
     *
     * @return the value of wx_user.id
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.id
     *
     * @param id the value for wx_user.id
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_name
     *
     * @return the value of wx_user.wx_name
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_name
     *
     * @param wxName the value for wx_user.wx_name
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    public void setWxName(String wxName) {
        this.wxName = wxName == null ? null : wxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.create_time
     *
     * @return the value of wx_user.create_time
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.create_time
     *
     * @param createTime the value for wx_user.create_time
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}