package com.btba.dao;

import com.btba.dataobject.WxUserDO;

public interface WxUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    int insert(WxUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    int insertSelective(WxUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    WxUserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    int updateByPrimaryKeySelective(WxUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Fri May 17 10:55:26 CST 2019
     */
    int updateByPrimaryKey(WxUserDO record);

    WxUserDO searchByWxName(String wxName);
}